/* DSblock model generated by Dymola from Modelica model Grate.Fuels.FuelSource
 Dymola Version 2016 (64-bit), 2015-04-15 translated this at Sat Sep 12 15:04:14 2015

  OutputCPUtime = true;
 */

#include <matrixop.h>
/* Declaration of C-structs */
/* Prototypes for functions used in model */
/* Codes used in model */
/* DSblock C-code: */

#define NX_    0
#define NX2_   0
#define NU_    0
#define NY_    15
#define NW_    9
#define NP_    15
#define NPS_   0
#define MAXAuxStr_   9
#define MAXAuxStrLen_   500
#define NHash1_ -1455660947
#define NHash2_ 465379918
#define NHash3_ 0
#define NI_    0
#define NRelF_ 0
#define NRel_  0
#define NTim_  0
#define NSamp_ 0
#define NCons_ 0
#define NA_    0
#define SizePre_ 0
#define SizeEq_ 0
#define SizeDelay_ 0
#define QNLmax_ 0
#define MAXAux 0
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 0
#define NGlobalHelpI_ 0
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif
#include <moutil.c>
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="Grate.Fuels.FuelSource";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=0;
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations
DYNX(Y_,13) = CurrentClockTime;
if (DYNEvent) DYNX(Y_,14) += 1;

InitialSection
DYNX(W_,0) = 15000000.0;
DYNX(W_,1) = true;
DYNX(W_,2) = false;
DYNSetAuxString(did_, "Moisture", 0);
DYNSetAuxString(did_, "Combustibles", 1);
DYNSetAuxString(did_, "Ash", 2);
DYNSetAuxString(did_, "Carbon", 3);
DYNSetAuxString(did_, "Hydrogen", 4);
DYNSetAuxString(did_, "Oxygen", 5);
DYNSetAuxString(did_, "Nitrogen", 6);
DYNSetAuxString(did_, "Sulfur", 7);
DYNSetAuxString(did_, "CO2", 8);
DYNX(Y_,1) = 15000000.0;
DYNX(Y_,12) = 1.0;
BoundParameterSection
DYNX(W_,3) = DYNX(DP_,6);
DYNX(W_,4) = DYNX(DP_,7);
DYNX(W_,5) = DYNX(DP_,8);
DYNX(W_,6) = DYNX(DP_,9);
DYNX(W_,7) = DYNX(DP_,10);
DYNX(W_,8) = DYNX(DP_,11);
DYNX(Y_,0) = DYNX(DP_,0);
DYNX(Y_,2) = DYNX(DP_,1);
DYNX(Y_,3) = DYNX(DP_,2);
DYNX(Y_,4) = divmacro(DYNX(DP_,12),"prox[1]",DYNX(DP_,12)+DYNX(DP_,13)+
  DYNX(DP_,14),"prox[1]+prox[2]+prox[3]");
DYNX(Y_,5) = divmacro(DYNX(DP_,13),"prox[2]",DYNX(DP_,12)+DYNX(DP_,13)+
  DYNX(DP_,14),"prox[1]+prox[2]+prox[3]");
DYNX(Y_,6) = divmacro(DYNX(DP_,14),"prox[3]",DYNX(DP_,12)+DYNX(DP_,13)+
  DYNX(DP_,14),"prox[1]+prox[2]+prox[3]");
DYNX(Y_,7) = divmacro(DYNX(W_,3),"ulti[1]",DYNX(W_,3)+DYNX(W_,4)+DYNX(W_,5)+
  DYNX(W_,6)+DYNX(W_,7),"ulti[1]+ulti[2]+ulti[3]+ulti[4]+ulti[5]");
DYNX(Y_,8) = divmacro(DYNX(W_,4),"ulti[2]",DYNX(W_,3)+DYNX(W_,4)+DYNX(W_,5)+
  DYNX(W_,6)+DYNX(W_,7),"ulti[1]+ulti[2]+ulti[3]+ulti[4]+ulti[5]");
DYNX(Y_,9) = divmacro(DYNX(W_,5),"ulti[3]",DYNX(W_,3)+DYNX(W_,4)+DYNX(W_,5)+
  DYNX(W_,6)+DYNX(W_,7),"ulti[1]+ulti[2]+ulti[3]+ulti[4]+ulti[5]");
DYNX(Y_,10) = divmacro(DYNX(W_,6),"ulti[4]",DYNX(W_,3)+DYNX(W_,4)+DYNX(W_,5)+
  DYNX(W_,6)+DYNX(W_,7),"ulti[1]+ulti[2]+ulti[3]+ulti[4]+ulti[5]");
DYNX(Y_,11) = divmacro(DYNX(W_,7),"ulti[5]",DYNX(W_,3)+DYNX(W_,4)+DYNX(W_,5)+
  DYNX(W_,6)+DYNX(W_,7),"ulti[1]+ulti[2]+ulti[3]+ulti[4]+ulti[5]");
InitialSection
InitialSection
InitialStartSection
InitialSection
DefaultSection
InitializeData(0)
InitialSection
InitialSection2
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection

DynamicsSection

AcceptedSection1

AcceptedSection2

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareParameter("m_flow", "Mass flow of the fuel [kg/s]", 0, 1, 0.0,0.0,0.0,0,560)
DeclareVariable("heating_value", "Heating Value of the fuel at temperature T [J/kg|MJ/kg]",\
 15000000.0, 0.0,0.0,0.0,0,513)
DeclareParameter("rho", "Density of the fuel [kg/m3|g/cm3]", 1, 1, 0.0,1E+100,\
0.0,0,560)
DeclareParameter("T", "Temperature of the fuel [K|degC]", 2, 298.15, 0.0,1E+100,\
300.0,0,560)
DeclareParameter("prox_moi", "Mass fraction of Moisture [1]", 3, 1, 0.0,1.0,0.0,\
0,560)
DeclareParameter("prox_com", "Mass fraction of Combustibles [1]", 4, 1, 0.0,1.0,\
0.0,0,560)
DeclareParameter("prox_ash", "Mass fraction of Ash [1]", 5, 1, 0.0,1.0,0.0,0,560)
DeclareVariable("use_ultimate", "Use ultimate analasis data [:#(type=Boolean)]",\
 true, 0.0,0.0,0.0,0,1539)
DeclareParameter("ulti_C", "Mass fraction of Carbon (C) [1]", 6, 1, 0.0,1.0,0.0,\
0,560)
DeclareParameter("ulti_H", "Mass fraction of Hydrogen (H) [1]", 7, 1, 0.0,1.0,\
0.0,0,560)
DeclareParameter("ulti_O", "Mass fraction of Oxygen (O) [1]", 8, 1, 0.0,1.0,0.0,\
0,560)
DeclareParameter("ulti_N", "Mass fraction of Nitrogen (N) [1]", 9, 1, 0.0,1.0,\
0.0,0,560)
DeclareParameter("ulti_S", "Mass fraction of Sulfur (S) [1]", 10, 1, 0.0,1.0,0.0,\
0,560)
DeclareVariable("use_spicies", "Use spicies analasis data [:#(type=Boolean)]", \
false, 0.0,0.0,0.0,0,1539)
DeclareParameter("spicies_CO2", "Mass fraction of CO2 [1]", 11, 1, 0.0,1.0,0.0,0,560)
DeclareParameter("prox[1]", "[1]", 12, 1, 0.0,1.0,0.0,0,2608)
DeclareParameter("prox[2]", "[1]", 13, 1, 0.0,1.0,0.0,0,2608)
DeclareParameter("prox[3]", "[1]", 14, 1, 0.0,1.0,0.0,0,2608)
DeclareVariable("ulti[1]", "[1]", 0.0, 0.0,1.0,0.0,0,2561)
DeclareVariable("ulti[2]", "[1]", 0.0, 0.0,1.0,0.0,0,2561)
DeclareVariable("ulti[3]", "[1]", 0.0, 0.0,1.0,0.0,0,2561)
DeclareVariable("ulti[4]", "[1]", 0.0, 0.0,1.0,0.0,0,2561)
DeclareVariable("ulti[5]", "[1]", 0.0, 0.0,1.0,0.0,0,2561)
DeclareVariable("spicies[1]", "[1]", 0.0, 0.0,1.0,0.0,0,2561)
DeclareOutput("fuelOutput1.m_flow", "[kg/s]", 0, 0.0, 0.0,0.0,0.0,0,521)
DeclareOutput("fuelOutput1.heating_value", "[J/kg]", 1, 15000000.0, 0.0,0.0,0.0,\
0,521)
DeclareOutput("fuelOutput1.rho", "[kg/m3|g/cm3]", 2, 0.0, 0.0,1E+100,0.0,0,521)
DeclareOutput("fuelOutput1.T", "[K|degC]", 3, 288.15, 0.0,1E+100,300.0,0,521)
DeclareOutput("fuelOutput1.prox[1]", "[1]", 4, 0.0, 0.0,1.0,0.0,0,521)
DeclareOutput("fuelOutput1.prox[2]", "[1]", 5, 0.0, 0.0,1.0,0.0,0,521)
DeclareOutput("fuelOutput1.prox[3]", "[1]", 6, 0.0, 0.0,1.0,0.0,0,521)
DeclareOutput("fuelOutput1.ulti[1]", "[1]", 7, 0.0, 0.0,1.0,0.0,0,521)
DeclareOutput("fuelOutput1.ulti[2]", "[1]", 8, 0.0, 0.0,1.0,0.0,0,521)
DeclareOutput("fuelOutput1.ulti[3]", "[1]", 9, 0.0, 0.0,1.0,0.0,0,521)
DeclareOutput("fuelOutput1.ulti[4]", "[1]", 10, 0.0, 0.0,1.0,0.0,0,521)
DeclareOutput("fuelOutput1.ulti[5]", "[1]", 11, 0.0, 0.0,1.0,0.0,0,521)
DeclareOutput("fuelOutput1.spicies[1]", "[1]", 12, 1.0, 0.0,1.0,0.0,0,521)
DeclareOutput("CPUtime", "", 13, 0.0, 0.0,0.0,0.0,0,512)
DeclareOutput("EventCounter", "", 14, 0.0, 0.0,0.0,0.0,0,512)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_) {
static Real initStore[1];
}
StartDataBlock
EndDataBlock
